---
# --------------------------------

- name: "Include variable"
  ansible.builtin.include_tasks:
    file: variables.yml
  tags: [ct-dnsmasq]

- name: "Include tasks (FF)"
  ansible.builtin.include_tasks:
    file: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version.split('.')[0] }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - default.yml
      paths:
      - "tasks"
  tags: [ct-dnsmasq]

- name: "Enable and unmask Dnsmasq service"
  ansible.builtin.systemd:
    name: "{{ dnsmasq_svc_name }}"
    enabled: "{{ dnsmasq_svc_enabled | bool }}"
    masked: "{{ dnsmasq_svc_masked | bool }}"
  become: true
  tags: [ct-dnsmasq]

# --------------------------------
...
