---
# --------------------------------

- name: "RedHat : Install packages"
  ansible.builtin.yum:
    name: "{{ dnsmasq_pkg_names.redhat }}"
    state: "{{ dnsmasq_state }}"
    update_cache: "{{ dnsmasq_update_cache }}"
  become: true
  tags: [ct-dnsmasq]

# --------------------------------
...
