---
# --------------------------------

- name: "Install packages"
  ansible.builtin.dnf:
    name: "{{ dnsmasq_pkg_names }}"
    state: "{{ dnsmasq_state }}"
    update_cache: "{{ dnsmasq_update_cache }}"
  become: true
  tags: [ct-dnsmasq]

- name: "Get status of old resolver file (check_mode=false)"
  ansible.builtin.stat:
    path: "{{ dnsmasq_resolv_conf }}"
  check_mode: false
  register: stat_resolver
  tags: [ct-dnsmasq]

- name: "Remove old resolver file if it is a symlink"
  ansible.builtin.file:
    path: "{{ dnsmasq_resolv_conf }}"
    state: absent
  when:
  - (stat_resolver.stat.islnk is defined and stat_resolver.stat.islnk) or (stat_resolver.stat.isfile is defined and stat_resolver.stat.isfile)
  notify: RestartDnsmasq
  become: true
  tags: [ct-dnsmasq]

# https://aws.amazon.com/premiumsupport/knowledge-center/ec2-static-dns-ubuntu-debian/
- name: "Rocky : Inject line into  /etc/dhcp/dhclient.conf"
  ansible.builtin.lineinfile:
    line: "supersede domain-name-servers 127.0.0.1;"
    path: /etc/dhcp/dhclient.conf
    regexp: "^supersede domain-name-servers"
    state: present
  notify: RestartDnsmasq
  become: true
  when: false  # keep handy for now
  # when: ansible_os_family == "RedHat" and ansible_distribution != "Rocky"
  tags: [ct-dnsmasq]

- name: "Render NetworkManager config file"
  ansible.builtin.template:
    src: NetworkManager.conf.j2
    dest: "{{ dnsmasq_networkmanager_cfg_dir }}/{{ dnsmasq_networkmanager_cfg_file }}"
    group: root
    mode: "0644"
    owner: root
  notify:
  - RestartDnsmasq
  - RestartNetworkManager
  become: true
  tags: [ct-dnsmasq]

- name: "Render Dnsmasq config file"
  ansible.builtin.template:
    src: default.j2
    dest: "{{ dnsmasq_cfg_dir }}/{{ dnsmasq_cfg_file }}"
    group: root
    mode: "0644"
    owner: root
  notify:
  - RestartDnsmasq
  - RestartNetworkManager
  become: true
  tags: [ct-dnsmasq]

- name: "Render resolver config"
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: "{{ dnsmasq_resolv_conf }}"
    group: root
    mode: "0644"
    owner: root
  notify:
  - RestartDnsmasq
  - RestartNetworkManager
  become: true
  tags: [ct-dnsmasq]

- name: "Render details of fallback resolver"
  ansible.builtin.template:
    src: forwarding_nameserver.j2
    dest: "{{ dnsmasq_fallback_conf }}"
    group: root
    mode: "0644"
    owner: root
  notify:
  - RestartDnsmasq
  - RestartNetworkManager
  become: true
  tags: [ct-dnsmasq]

# --------------------------------
...
